### ISSUE TITLE
Case sensitivity for linux mods

### ISSUE THREAD

**Issue by MitchDrage** [Dahlgren/node-arma-server#34]
I'm hitting an issue with loading mod pbos where log errors are showing that the linux server is ignoring the case sensitivity in mods when booting:
`ErrorMessage: Cannot open file '/arma3/@RHSUSF\addons\rhsusf_editorpreviews'`

Where the file name is actually:
`rhsusf_editorPreviews.pbo`

**Comment by MitchDrage** [comment]
Raised in error. Should have been on your arma-server-web-admin, but is likely to be a mod/linux issue rather than with your work.

**Comment by Dahlgren** [comment]
Yeah, folders and files should generally be lower case or you'll run into problems with the linux server. You could also mount the arma server folder as a virtual case insensitive fs.
